### ISSUE TITLE
Suggestion : move CurrentListingFocused from UILobbyListing to UIGameServers

### ISSUE THREAD

**Issue by LazerGoat** [valkyrienyanko/GodotModules#28]
Haven't had time to look at much but I noticed something about the way server listings are selected that could potentially cause problems later.

1)
![image](https://user-images.githubusercontent.com/47578360/164055727-cfce004f-0b78-4cbe-96cd-05cdadf3163b.png)

2)
![image](https://user-images.githubusercontent.com/47578360/164056151-42818e3a-9f06-4534-bcf7-18b695effe18.png)

3)
![image](https://user-images.githubusercontent.com/47578360/164056599-7c27aebd-9fd2-4733-81fe-9d8b2d020eb4.png)

4)
![image](https://user-images.githubusercontent.com/47578360/164056732-8bd0122c-40dc-4a91-808b-4db3af405e14.png)

5) Finally this solves the problem for the join button in the server list's button bar
![image](https://user-images.githubusercontent.com/47578360/164056915-a20a1dfd-ec4f-49cd-be3e-c7e5eb0a109a.png)

**Comment by valkyrienyanko** [comment]
Thank you 

The following commit has applied these changes --> b8530df059f228a2e0b3e8dd53e02040b01a7f28
